<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-25T12:15:36 IST" name="AutomationSuite" finished-at="2025-07-25T12:15:48 IST" duration-ms="11824">
    <groups>
      <group name="smoke">
        <method signature="LoginTest.LoginToSiteNegative()[pri:0, instance:tests.LoginTest@57db2b13]" name="LoginToSiteNegative" class="tests.LoginTest"/>
        <method signature="LoginTest.LoginToSite()[pri:1, instance:tests.LoginTest@57db2b13]" name="LoginToSite" class="tests.LoginTest"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2025-07-25T12:15:36 IST" name="SeleniumTests" finished-at="2025-07-25T12:15:48 IST" duration-ms="11824">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:tests.LoginTest@57db2b13]" started-at="2025-07-25T12:15:36 IST" name="setUp" finished-at="2025-07-25T12:15:40 IST" duration-ms="3850" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="LoginToSiteNegative()[pri:0, instance:tests.LoginTest@57db2b13]" started-at="2025-07-25T12:15:40 IST" name="LoginToSiteNegative" finished-at="2025-07-25T12:15:41 IST" duration-ms="1106" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[not same title expected [Automation Exercise] but found [Automation Exercise - Signup / Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: not same title expected [Automation Exercise] but found [Automation Exercise - Signup / Login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at tests.LoginTest.LoginToSiteNegative(LoginTest.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToSiteNegative -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginTest@57db2b13]" started-at="2025-07-25T12:15:41 IST" name="tearDown" finished-at="2025-07-25T12:15:41 IST" duration-ms="249" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:tests.LoginTest@57db2b13]" started-at="2025-07-25T12:15:41 IST" name="setUp" finished-at="2025-07-25T12:15:45 IST" duration-ms="3508" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="LoginToSite()[pri:1, instance:tests.LoginTest@57db2b13]" started-at="2025-07-25T12:15:45 IST" name="LoginToSite" finished-at="2025-07-25T12:15:47 IST" duration-ms="2646" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToSite -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginTest@57db2b13]" started-at="2025-07-25T12:15:47 IST" name="tearDown" finished-at="2025-07-25T12:15:48 IST" duration-ms="295" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.LoginTest -->
    </test> <!-- SeleniumTests -->
  </suite> <!-- AutomationSuite -->
</testng-results>
